ALTER TYPE "NoteType" ADD VALUE IF NOT EXISTS 'SHOPPING';
ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "isForConfidant" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "links" JSONB;
