CREATE TYPE "NoteType" AS ENUM ('JOURNAL','BOOK','SERIES','MOVIE','MUSIC','OUTING');
ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "noteType" "NoteType" NOT NULL DEFAULT 'JOURNAL';
ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "mediaMeta" JSONB;
