-- Add new TaskStatus enum values
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'LOCAL_DONE';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'DEPLOYED';
